### ISSUE TITLE
Grafana workflow in wiki plus needed code/templates

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#126]
**Is your feature request related to a problem? Please describe.**
Describe a visual workflow for setting up graphs in grafana

**Describe the solution you'd like**
Grafana guide for setting up and viewing ARTEMIS graphs. Example: BGP updates/second

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by leopoul** [comment]
If I find some spare time I could contribute to that. Have a dashboard with origin AS and prefix as template variables. Hijacks could be annotated as events. BGP updates could be also annotated as events and used in other graphs, eg. a traffic graph etc, to ease visual correlation and quick root cause analysis on a screen, depends on use case.
<img width="1583" alt="screen shot 2019-03-01 at 22 46 34" src="https://user-images.githubusercontent.com/770064/53770260-c9c05e00-3ede-11e9-917d-38a2ea24ec03.png">

**Comment by vkotronis** [comment]
@leopoul that would be great, very nice idea! To begin with we need a Proof of Concept setup that can help the user use Grafana with 1-2 examples. For now, I am moving this issue to the release after the coming one, i.e., the 1.3.0 release.

**Comment by vkotronis** [comment]
@leopoul any ideas on producing a dashboard such as the one you show here? We would ideally like to use grafana to automatically create some useful figures for the operator and update them (ideally async, in the worst case via polling) in real-time. @slowr if you could also help with this it would be a great addition to the current software package (everything should be addressed by code/templates on the grafana container, for modularity).

**Comment by vkotronis** [comment]
@slowr any ideas on this issue? To be able to easily plot useful things like BGP updates/sec using templated queries? We mainly need the proper instructions to do this.
