### ISSUE TITLE
Withdrawal logging capability

### ISSUE THREAD

**Issue by smith8917** [FORTH-ICS-INSPIRE/artemis#230]
To better track the transient nature of BGP Hijacks on systems that are tied to ARTEMIS alerting (syslog, service now, slack, etc), we'd like it if the backend logging capabilities were expanded to alert when a hijack is completely cleared/withdrawn.  

It's preferred to have the log be in JSON format like the existing hijack alerts.

Additionally, if the "message" were configurable to add/remove attributes that are key to our deployment/operations team, that would also be beneficial.  As part of the "message", providing a link to the ARTEMIS system page displaying the details would also be advantageous

As always, thank you and keep up the great work, we're finding this system to be extremely useful!

**Comment by vkotronis** [comment]
Will require a hijack and email logger similar to detection in the database access module.
The hijack logger will also record peer withdrawals, as well as fully withdrawn hijacks.
The mail logger will include only fully withdrawn hijacks.
We can also do the same for the outdated hijack alerts, since they are not hijacks any more due to the change in configuration.

Regarding the fields to add/remove, I plan to add an .env variable (HIJACK_LOG_FIELDS) where the user will input a list of attributes that need to be in the message (with some default options), and then a filter (additional to what we have now with communities will keep only those fields in the message), both for the email and hijack logger.

I will work on this next week, to be included in the next minor release.

**Comment by smith8917** [comment]
@vkotronis - this all sounds like exactly what we're looking for, thanks for working on it

**Comment by vkotronis** [comment]
@smith8917 I did some checks and we cannot at this point integrate also the "peers_withdrawn" extra field in the logs because of a possible race condition between detection and database access.
This info will remain visible in the UI of course. However, the logs will include fully withdrawn, resolved, ignored, outdated and deleted hijacks. I have done the first part in my ongoing PR, now what remains is the selective inclusion of fields. The available fields to choose from will be:
```
[
  "prefix",
   "hijack_as",
   "type",
   "time_started",
   "time_last",
   "peers_seen",
   "monitor_keys",
   "configured_prefix",
   "timestamp_of_config",
   "asns_inf",
   "time_detected",
   "key",
   "community_annotation",
  "end_tag"
]
```
I will let you know when I merge the changes.

**Comment by smith8917** [comment]
great, and i see you've added the hijack_url too 👍
