### ISSUE TITLE
Show user that configuration is still loading when it takes time

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis#365]
**Is your feature request related to a problem? Please describe.**
Right now you can specify a configuration and you will receive that is accepted. After reloading though you will see the old configuration and this is due to the modules being stuck on building the prefix tree which might take even minutes!

**Describe the solution you'd like**
There needs to be a progress bar that actually let's user know that we are currently loading the new configuration and that it is not stuck on an unknown behavior or that it didn't pick up the new configuration at all.

**Comment by pixitha** [comment]
I would love the ability to see the loading of the database and such without having to watch the docker logs!

**Comment by vkotronis** [comment]
@slowr this progress can be probably stored in the database (e.g., every second or so), and a frontend progress bar loader could use a graphql call to update its state. However do we need this to show only the progress of the DB module or also the rest? The relative call is `build_prefix_tree()` (see [this line](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/backend/core/database.py#L678). So what I would propose:

1) on the backend: DB table where the prefix tree builder writes per module rows as follows:
```
module | total_rules | processed_rules | total_prefixes | processed_prefixes
```
I am not sure how we can get the total_prefixes though since to calculate this number we need to translated everything in advance and do twice the calls (maybe you can refactor the `build_prefix_tree()` call to be more efficient).

2) on the frontend: graphql call so that the content of the table can be retrieved asynchronously. We could show 2 percentages on the conf screen: one based on the rule number (easier) and one based on the prefix number (harder, see comment above). Could you maybe collaborate with @pgigis to find the most visually pleasing way to show this to a user?

I think the challenging part if efficiently estimating the total number of prefixes to process before processing them in the prefix tree builder. What do you think? Let me know on the comments below.

**Comment by slowr** [comment]
> @slowr this progress can be probably stored in the database (e.g., every second or so), and a frontend progress bar loader could use a graphql call to update its state. However do we need this to show only the progress of the DB module or also the rest? The relative call is `build_prefix_tree()` (see [this line](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/backend/core/database.py#L678)). So what I would propose:
> 
> 1. on the backend: DB table where the prefix tree builder writes per module rows as follows:
> 
> ```
> module | total_rules | processed_rules | total_prefixes | processed_prefixes
> ```
> 
> I am not sure how we can get the total_prefixes though since to calculate this number we need to translate everything in advance and do twice the calls (maybe you can refactor the `build_prefix_tree()` call to be more efficient). The per-second DB writing could be based on a callback; this is something to be evaluated in the context of the current DB module. We can also simply write stuff to the DB every X prefixes (or rules) or so.
> 
> 1. on the frontend: graphql call so that the content of the table can be retrieved asynchronously. We could show 2 percentages on the conf screen: one based on the rule number (easier) and one based on the prefix number (harder, see comment above). Could you maybe collaborate with @pgigis to find the most visually pleasing way to show this to a user?
> 
> I think the challenging part if efficiently estimating the total number of prefixes to process before processing them in the prefix tree builder and properly installing the callback. What do you think? Let me know on the comments below.

We run this also on the monitor module, the tool needs to actually say the correct state of each module instead of just green/red and behind the scene it's stuck loading

**Comment by vkotronis** [comment]
Hmmm currently we use the following DB table to store states:
```
CREATE TABLE IF NOT EXISTS process_states (
    name VARCHAR (32) UNIQUE,
    running BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP default current_timestamp
);
```
And we determine if a module is running using the supervisor, e.g.,
```
for ctx in {BACKEND_SUPERVISOR_URI, MON_SUPERVISOR_URI}:
                    if not ctx:
                        continue
                    server = ServerProxy(ctx)
                    processes = [
                        (x["name"], x["state"] == 20)
                        for x in server.supervisor.getAllProcessInfo()
                        if x["name"] != "listener"
                    ]
                    # do sth with the process info
```
However this checks only if the process is up, not if it is loading sth. So could we address this issue by having by default a "yellow" state until the module has finished its initialization/reloading tasks? This can be signaled over a "state" exchange. E.g., when the module is up according to supervisor, we put it in the yellow state and when the module has signaled that it is done, we put it in green state. This does not affect the backend semantics, only the frontend and offers some info (maybe not percentages, but a signal that the module is loading) to the user. It would require no changes in the DB, but a new exchange where the "loading done" signal is sent when the modules have finished loading. Or we can also write this in the DB so that the frontend can easily pick it up with a graphql call, instead of implementing another exchange on the frontend.

So: 
1. We create a new "module_state" exchange
2. When a module boots, the supervisor picks it up, as well as the frontend (no change needed); however it would be put with a yellow instead of green color until the other signal is received.
3. Each module sends a "loading_done" signal to this exchange when they boot and finish their (re)loading stage (typically after the config rpc has been concluded).
4. The DB, which is subscribed to this exchange, picks up the signals and writes them on the process_state table (we need another column probably sth like "loading_finished", default=false)
5. The frontend using graphql queries changes on the "process_state" table, and when the "loading_finished" column is set to True for a module, it sets the color to green.

What do you think? In my opinion this would be a simple way to convey to the user that a module is loading.

**Comment by slowr** [comment]
> Hmmm currently we use the following DB table to store states:
> 
> ```
> CREATE TABLE IF NOT EXISTS process_states (
>     name VARCHAR (32) UNIQUE,
>     running BOOLEAN DEFAULT FALSE,
>     timestamp TIMESTAMP default current_timestamp
> );
> ```
> 
> And we determine if a module is running using the supervisor, e.g.,
> 
> ```
> for ctx in {BACKEND_SUPERVISOR_URI, MON_SUPERVISOR_URI}:
>                     if not ctx:
>                         continue
>                     server = ServerProxy(ctx)
>                     processes = [
>                         (x["name"], x["state"] == 20)
>                         for x in server.supervisor.getAllProcessInfo()
>                         if x["name"] != "listener"
>                     ]
>                     # do sth with the process info
> ```
> 
> However this checks only if the process is up, not if it is loading sth. So could we address this issue by having by default a "yellow" state until the module has finished its initialization/reloading tasks? This can be signaled over a "state" exchange. E.g., when the module is up according to supervisor, we put it in the yellow state and when the module has signaled that it is done, we put it in green state. This does not affect the backend semantics, only the frontend and offers some info (maybe not percentages, but a signal that the module is loading) to the user. It would require no changes in the DB, but a new exchange where the "loading done" signal is sent when the modules have finished loading. Or we can also write this in the DB so that the frontend can easily pick it up with a graphql call, instead of implementing another exchange on the frontend.
> 
> So:
> 
> 1. We create a new "module_state" exchange
> 2. When a module boots, the supervisor picks it up, as well as the frontend (no change needed); however it would be put with a yellow instead of green color until the other signal is received.
> 3. Each module sends a "loading_done" signal to this exchange when they boot and finish their (re)loading stage (typically after the config rpc has been concluded).
> 4. The DB, which is subscribed to this exchange, picks up the signals and writes them on the process_state table (we need another column probably sth like "loading_finished", default=false)
> 5. The frontend using graphql queries changes on the "process_state" table, and when the "loading_finished" column is set to True for a module, it sets the color to green.
> 
> What do you think? In my opinion this would be a simple way to convey to the user that a module is loading.

This seems like the best approach and minimizes the stuff we need to do as well

**Comment by vkotronis** [comment]
Great I will draft an implementation PR and notify when ready!
