### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by Sivolen** [FORTH-ICS-INSPIRE/artemis#664]
Hi!
Help me please 
[error_log.txt](https://github.com/FORTH-ICS-INSPIRE/artemis/files/9885382/error_log.txt)

I updated according to the documentation, but after updating on the front I get an error 502.
Clipping from the logs in the attachment, can you tell me what's wrong?

**Comment by vkotronis** [comment]
This was a problematic update in the frontend we will update the container and ping to download the new microservice

**Comment by vkotronis** [comment]
Fixed in https://github.com/FORTH-ICS-INSPIRE/artemis-web/pull/165 (frontend side)

Please follow https://github.com/FORTH-ICS-INSPIRE/artemis-web/pull/165 for the upgrade. We will issue the official release early next week, for now since you are working on the `latest` version you can follow these instructions.

If anything comes up, let us know please. Thanks @Sivolen !
