### ISSUE TITLE
Restoring from database backup fails

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#87]
**Describe the bug**
Trying to follow the wiki for restoring the database but its failing on import as it thinks all of the tables already exist

**Affected Component(s)**
- [x] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [x] Docs
- [ ] Build System

**To Reproduce**
1. Install a fresh release or git clone
2. Try to follow [wiki](https://github.com/FORTH-ICS-INSPIRE/artemis/wiki/Restoring-DB-from-backup)

**Expected behavior**
It should just fill all of the data from the old db into the new one.

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. iOS] RHEL7.6
 - Browser [e.g. chrome, safari] n/a
 - Version [e.g. 22] 1.1.0

**Additional context**
[postgres_errors.txt](https://github.com/FORTH-ICS-INSPIRE/artemis/files/2886709/postgres_errors.txt)

**Comment by vkotronis** [comment]
@pixitha @slowr I have updated the restoration instructions on https://github.com/FORTH-ICS-INSPIRE/artemis/wiki/Restoring-DB-from-backup . 

I tested those today morning with a mock DB.

@pixitha please check whether there are any issues with the current instructions. You can ignore the presented errors, these are due to pre-existing relationships (the data are correctly copied). If everything works correctly, we can close this issue and use the updated wiki page from now on.

@slowr please also double-check.

**Comment by vkotronis** [comment]
Closing issue since instructions seem to work (ignored errors are due to timescale mechanisms and do not affect the correctness of the db). Please re-open if further issues are encountered.
